server:
  port: ${PORT:0}

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog-dev
      port: ${PORT:0}
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
#  cloud:
#    config:
#      enabled: false

queue:
  movie:
    name: MovieRecords
  serie:
    name: SerieRecords

message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  health:
    circuitbrakers:
      enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      seriesmoviesfeing:
        allow-health-indicator-to-fail: false
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    configs:
      instances:
        seriesmoviesfeing:
          max-retry-attempts: 3
          wait-duration: 1000
          retry-exceptions:
            - feign.FeignException$InternalServerError
            - java.net.ConnectException
