server:
  port: ${PORT:0}

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog-dev
      port: ${PORT:0}
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
#  cloud:
#    config:
#      enabled: false

queue:
  movie:
    name: MovieRecords
  serie:
    name: SerieRecords

message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
