server:
  port: ${PORT:0}

spring:
  application:
    name: movie-service    
  datasource:
    url: jdbc:mysql://localhost:3306/movie-dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: general #change database credentials
    password: general #change database credentials
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:movie-service.sql

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
