server:
  port: ${PORT:0}

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: serie-dev
      port: 0
#  cloud:
#    config:
#      enabled: false

message: hello from serie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
